
SOURCES += dllmain.cpp
PROJECT_BASENAME = krglhjxl

RC_LEGALCOPYRIGHT ?= Copyright (C) 2022-2022 Julian Uy; See details of license at license.txt, or the source code location.

include external/tp_stubz/Rules.lib.make

DEPENDENCY_BUILD_DIRECTORY_LIBJXL := $(DEPENDENCY_BUILD_DIRECTORY)/libjxl

EXTLIBS += $(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/lib/libjxl.a $(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/lib/libjxl_threads.a $(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/third_party/highway/libhwy.a $(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/third_party/brotli/libbrotlicommon-static.a $(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/third_party/brotli/libbrotlidec-static.a
SOURCES += $(EXTLIBS)
OBJECTS += $(EXTLIBS)
LDLIBS += $(EXTLIBS)

INCFLAGS += -Iexternal/libjxl/lib/include -I$(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/lib/include
CFLAGS += -DJXL_STATIC_DEFINE -DJXL_THREADS_STATIC_DEFINE

$(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/lib/include/jxl/jxl_export.h: $(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/lib/libjxl.a

$(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/lib/libjxl_threads.a: $(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/lib/libjxl.a
$(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/third_party/highway/libhwy.a: $(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/lib/libjxl.a
$(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/third_party/brotli/libbrotlicommon-static.a: $(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/lib/libjxl.a
$(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/third_party/brotli/libbrotlidec-static.a: $(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/lib/libjxl.a

dllmain$(OBJECT_EXTENSION): $(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/lib/include/jxl/jxl_export.h

$(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)/lib/libjxl.a:
	cmake \
		-S external/libjxl \
		-B $(DEPENDENCY_BUILD_DIRECTORY_LIBJXL) \
		-DCMAKE_SYSTEM_NAME=Windows \
		-DCMAKE_SYSTEM_PROCESSOR=$(TARGET_CMAKE_SYSTEM_PROCESSOR) \
		-DCMAKE_FIND_ROOT_PATH=/dev/null \
		-DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
		-DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
		-DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
		-DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY \
		-DCMAKE_DISABLE_FIND_PACKAGE_PkgConfig=TRUE \
		-DCMAKE_C_COMPILER=$(CC) \
		-DCMAKE_CXX_COMPILER=$(CXX) \
		-DCMAKE_RC_COMPILER=$(WINDRES) \
		-DCMAKE_BUILD_TYPE=Release \
		-DJPEGXL_ENABLE_OPENEXR=FALSE \
		-DJPEGXL_ENABLE_TOOLS=FALSE \
		-DJPEGXL_ENABLE_BENCHMARK=FALSE \
		-DCMAKE_CXX_FLAGS="-DHWY_DISABLED_TARGETS=\"HWY_AVX2|HWY_AVX3\"" \
		-DJPEGXL_ENABLE_JNI=OFF \
		-DJPEGXL_ENABLE_MANPAGES=OFF \
		-DJPEGXL_BUNDLE_GFLAGS=ON \
		-DBUILD_TESTING=OFF \
		-DJPEGXL_ENABLE_TOOLS=OFF \
		-DJPEGXL_ENABLE_VIEWERS=OFF \
		&& \
	cmake --build $(DEPENDENCY_BUILD_DIRECTORY_LIBJXL)
